palette = {
    "''": "black",
    "``": "black",
    ",": "black",
    ".": "black",
    ":": "black",
    ".": "black",
    "-LRB-": "black",
    "HYPH": "black",
    "LS": "black",
    "SYM": "black",
    "CC": "brown",
    "cardinal number": "tab:gray",
    "CD": "tab:gray",
    "DT": "salmon",
    "EX": "rosybrown",
    "function word": "tab:purple",
    "IN": "tab:purple",
    "adjective": "tab:orange",
    "JJ": "tab:orange",
    "JJR": "gold",
    "JJS": "yellow",
    "MD": "rosybrown",
    "noun": "tab:blue",
    "NN": "tab:blue",
    "NNP": "navy",
    "NNS": "cadetblue",
    "PDT": "saddlebrown",
    "POS": "grey",
    "PRP": "tab:olive",
    "PRP$": "olivedrab",
    "adverb": "tab:pink",
    "RB": "tab:pink",
    "RBR": "magenta",
    "RBS": "palevioletred",
    "RP": "darkviolet",
    "TO": "indigo",
    "ADD": "tab:green",
    "FW": "tab:green",
    "GW": "tab:green",
    "NFP": "tab:green",
    "UH": "tab:green",
    "verb": "tab:red",
    "VB": "tab:red",
    "VBD": "salmon",
    "VBG": "orangered",
    "VBN": "chocolate",
    "VBP": "pink",
    "VBZ": "crimson",
    "WDT": "darkcyan",
    "WP": "slateblue",
    "WP$": "darkslateblue",
    "wh-word": "tab:cyan",
    "WRB": "tab:cyan",

    # noun subcategories
    "body_parts": "red",
    "clothing": "blue",
    "food_drink": "orange",
    "vehicles": "gray",
    "toys": "green",
    "animals": "pink",
    "household": "cyan",
    "places": "brown",
    "sounds": "yellow",
    "furniture_rooms": "maroon",
    "outside": "limegreen",
    "people": "fuchsia",
    "games_routines": "slategray",

    # verb subcategories
    "trans. verb": "gold",
    "intrans. verb": "purple",
    "(in)trans. verb": "peru",
    "special verb": "lime",
}