grids = [
    {
        "main_file": ["main.py"],
        "data_dir": ["word_use_data/childes/word", "word_use_data/ptb_text_only/word"][:1],
        "config": ["gpt2"],
        "lm": [True],
        "concat": [False, True][:1],
        "context_length": [128],
        "no_new_token": [False, True][:1],
        "freq_cutoff": [4],
        "n_epochs": [30],
        "batch_size": [8],
        "n_examples": list(range(4, 5)),
        "max_sample_times": [0],
        "eval_n_classes": [tuple(range(2, 7))],
        "loss_reduction": ["sum"],
        "lr": [1e-3, 3e-4, 1e-4, 3e-5, 1e-5],
        "weight_decay": [0.15, 0.12, 0.10, 0.07, 0.05][1:2],
        "factor": [0.1],
        "patience": [2],
        "seed": [0],
        "eval_seed": [0],
        "logging_step": [100],
    },
]
# ordered flags to display in job name
flags = [
    "data_dir",
    "config",
    "concat",
    "context_length",
    "no_new_token",
    "n_examples",
    "max_sample_times",
    "batch_size",
    "lr",
    "weight_decay",
    "seed",
]